show variables like 'datadir';

/* Modelagem básica - 
ENTIDADE = TABELA
CAMPOS = ATRIBUTOS */

CLIENTE
NOME 


/* Fase 1 e 2 ADM de dados */
Modelagem conceitual - Rascunho
Modelagem Lógica - Qualquer programa de Modelagem

/*Fase 3 - DBA / AD */
Modelagem Física - Scripts de Banco

/*INICIANDO A MODELAGEM FÍSICA*/


/*CRIANDO O BANCO DE DADOS*/
CREATE DATABASE PROJETO;
CREATE DATABASE EXEMPLO;

/*CONECTANDO AO BANCO*/
USE PROJETO;


/*CRIANDO TABLE CLIENTES*/

CREATE TABLE CLIENTE(
    NOME VARCHAR(30),
    SEXO CHAR(1),
    EMAIL VARCHAR(30),
    CPF INT(11),
    TELEFONE VARCHAR(30),
    ENDERECO VARCHAR(100)
);

--Verificando as tablas do banco
SHOW TABLES;


--DESCOBRINDO COMO É UMA ESTRUTURA DE UMA TABLELA

DESC CLIENTE;


--ALIAS DE COLUNAS
SELECT NOME, SEXO, EMAIL FROM CLIENTE;

SELECT NOME AS CLIENTE, SEXO, EMAIL FROM CLIENTE;

SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE;
-- POSSO PROJETAR NA ORDEM QUE EU QUISER
SELECT SEXO, EMAIL, ENDERECO, NOME FROM CLIENTE;

SELECT SEXO, EMAIL, ENDERECO, NOME, NOW() AS DATA_HORA FROM CLIENTE;

--APENAS PARA FINS ACADÊMICOS
SELECT * FROM CLIENTE;

SELECT NOME, SEXO FROM CLIENTE
WHERE SEXO = 'M';

SELECT NOME, ENDERECO FROM CLIENTE
WHERE SEXO = 'F';

SELECT NOME, ENDERECO, SEXO FROM CLIENTE
WHERE SEXO = 'F';

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO = 'RJ';

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO = 'RJ';
--EMPTY SET


-- UTILIZANDO O COMANDO LIKE
SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO LIKE 'RJ';
--EMPTY SET

/*CARACTER CORINGA % -> QUALQUER COISA*/
-- PROCURANDO QUEM TEM RJ NO FINAL DO ENDERECO
SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO LIKE '%RJ';


SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO LIKE 'OSCAR CURY%';

SELECT * FROM CLIENTE;
--PROCURANDO NO MEIO
SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE ENDERECO LIKE '%CENTRO%';



--AULA 18--
--NÃO ESQUEÇA DE COLOCAR NO GIT--