show variables like 'datadir';

/* Modelagem básica - 
ENTIDADE = TABELA
CAMPOS = ATRIBUTOS */

CLIENTE
NOME 


/* Fase 1 e 2 ADM de dados */
Modelagem conceitual - Rascunho
Modelagem Lógica - Qualquer programa de Modelagem

/*Fase 3 - DBA / AD */
Modelagem Física - Scripts de Banco

/*INICIANDO A MODELAGEM FÍSICA*/


/*CRIANDO O BANCO DE DADOS*/
CREATE DATABASE PROJETO;
CREATE DATABASE EXEMPLO;

/*CONECTANDO AO BANCO*/
USE PROJETO;


/*CRIANDO TABLE CLIENTES*/

CREATE TABLE CLIENTE(
    NOME VARCHAR(30),
    SEXO CHAR(1),
    EMAIL VARCHAR(30),
    CPF INT(11),
    TELEFONE VARCHAR(30),
    ENDERECO VARCHAR(100)
);

--Verificando as tablas do banco
SHOW TABLES;


--DESCOBRINDO COMO É UMA ESTRUTURA DE UMA TABLELA

DESC CLIENTE;


--ALIAS DE COLUNAS
SELECT NOME, SEXO, EMAIL FROM CLIENTE;

SELECT NOME AS CLIENTE, SEXO, EMAIL FROM CLIENTE;

SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE;
-- POSSO PROJETAR NA ORDEM QUE EU QUISER
SELECT SEXO, EMAIL, ENDERECO, NOME FROM CLIENTE;

SELECT SEXO, EMAIL, ENDERECO, NOME, NOW() AS DATA_HORA FROM CLIENTE;

--APENAS PARA FINS ACADÊMICOS
SELECT * FROM CLIENTE;

SELECT NOME, SEXO FROM CLIENTE
WHERE SEXO = 'M';

SELECT NOME, ENDERECO FROM CLIENTE
WHERE SEXO = 'F';

SELECT NOME, ENDERECO, SEXO FROM CLIENTE
WHERE SEXO = 'F';

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO = 'RJ';

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO = 'RJ';
-- ESTE COMANDO MOSTRA "EMPTY SET"


-- UTILIZANDO O COMANDO LIKE
SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO LIKE 'RJ';
-- ESTE COMANDO MOSTRA "EMPTY SET"



/*CARACTER CORINGA % -> QUALQUER COISA*/
-- PROCURANDO QUEM TEM RJ NO FINAL DO ENDERECO
SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO LIKE '%RJ';


SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO LIKE 'OSCAR CURY%';

SELECT * FROM CLIENTE;
--PROCURANDO NO MEIO
SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE ENDERECO LIKE '%CENTRO%';



--AULA 19--
--NÃO ESQUEÇA DE COLOCAR NO GIT--

--EXERCÍCIO LIVRARIA--

/* Resolvendo o exercício */

CREATE DATABASE LIVRARIA;

USE LIVRARIA;

CREATE TABLE LIVROS(
	LIVRO VARCHAR(100),
	AUTOR VARCHAR(100),
	SEXO CHAR(1),
	PAGINAS INT(5),
	EDITORA VARCHAR(30),
	VALOR FLOAT(10,2),
	UF CHAR(2),
	ANO INT(4)
);

/* VERIFICANDO OS BANCOS */
SHOW DATABASES;

/* CONEVCTANDO A UM BANCO */
USE LIVRARIA;

SHOW TABLES;

--DESCRIÇÃO DA TABELA
DESC LIVROS;


INSERT INTO LIVROS VALUES('Cavaleiro Real','Ana Claudia','F',465,'Atlas',49.9,'RJ',2009);
INSERT INTO LIVROS VALUES('SQL para leigos','João Nunes','M',450,'Addison',98,'SP',2018);
INSERT INTO LIVROS VALUES('Receitas Caseiras','Celia Tavares','F',210,'Atlas',45,'RJ',2008);
INSERT INTO LIVROS VALUES('Pessoas Efetivas','Eduardo Santos','M',390,'Beta',78,'RJ',2018);
INSERT INTO LIVROS VALUES('Habitos Saudáveis','Eduardo Santos','M',630,'Beta',150,'RJ',2019);
INSERT INTO LIVROS VALUES('A Casa Marrom','Hermes Macedo','M',250,'Bubba',60,'MG',2016);
INSERT INTO LIVROS VALUES('Estacio Querido','Geraldo Francisco','M',310,'Insignia',100,'ES',2015);
INSERT INTO LIVROS VALUES('Pra sempre amigas','Leda Silva','F',510,'Insignia',78,'ES',2011);
INSERT INTO LIVROS VALUES('Copas Inesqueciveis','Marco Alcantara','M',200,'Larson',130,'RS',2018);
INSERT INTO LIVROS VALUES('O poder da mente','Clara Mafra','F',120,'Continental',56,'SP',2017);


--1 - TRAZER TODOS OS DADOS
SELECT * FROM LIVROS;

--2 - TRAZER O NOME DO LIVRO E DA EDITORA
SELECT LIVRO, EDITORA FROM LIVROS;

--3 - TRAZER O NOME DO LIVRO E A UF DOS LIVROS PUBLICADOS POR AUTORES DO SEXO MASCULINO
SELECT LIVRO, UF, SEXO FROM LIVROS
WHERE SEXO = 'M';

--4 - TRAZER O NOME DO LIVRO E O NÚMERO DE PÁGINAS DOS LIVROS PUBLICADOS POR AUTORES DO SEXO FEMININO
SELECT LIVRO, PAGINAS FROM LIVROS
WHERE SEXO = 'F';

--5 - TRAZER OS VALORES DOS LIVROS DAS EDITORAS SÃO PAULO
SELECT LIVRO, VALOR FROM LIVROS
WHERE EDITORA = 'SP';

--6 - TRAZER OS DADOS DOS AUTORES DO SEXO MASCULINP QUE TIVERAM LIVROS PUBLICADOS POR SÃO PAULO OU RIO DE JANEIRO



-- continuar na aula 21