-- CRIANDO O BANCO DE DADOS NO MYSQL
CREATE DATABASE ATIVIDADE1;
--COMANDO PARA ENTRAR NO BANCO DE DADOS
USE ATIVIDADE1;
--CRIANDO A PRIMEIRA TABELA
-- A CRIAÇÃO DAS TABELAS ESTÁ NA ORDEM CERTA, SEGUINDO A REGRA DE CRIAÇÃO DE TABELA COM CHAVES ESTRANGEIRAS
-- A TABELA QUE TIVER CHAVE ESTRANGEIRA DEVE SER CRIADA DEPOIS E COLOCAR A REFERENCIA DA TABELA ANTERIIOR
CREATE TABLE CLIENTE(
    IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR (100),
	RUA VARCHAR (100),
	NUMERO INT
);
--CRIANDO A TABELA PEDIDO COM A CHAVE ESTRANGEIRA IDCLIENTE DA TABELA CLIENTE
CREATE TABLE PEDIDO(
	IDPEDIDO INT PRIMARY KEY AUTO_INCREMENT,
	DESCRICAO VARCHAR(100),
	DATAPEDIDO DATE,
	ID_CLIENTE INT,
	FOREIGN KEY(ID_CLIENTE)	REFERENCES CLIENTE(IDCLIENTE)
);

---CRIANDO A TABELA PRODUTO
CREATE TABLE PRODUTO(
	IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
	DESCRICAO VARCHAR(100),
	PRECO REAL
);
---CRIANDO A TABELA ITEMPEDIDO COM A CHAVE ESTRANGEIA DE PRODUTO "IDPRODUTO"
CREATE TABLE ITEMPEDIDO(
	IDITEM INT PRIMARY KEY AUTO_INCREMENT,
	QUANTIDADE INT,
	VALOR REAL,
	ID_PRODUTO INT,
	FOREIGN KEY(ID_PRODUTO)	REFERENCES PRODUTO(IDPRODUTO)
);

---INSERINDO DADOS NA TABELA CLIENTE
INSERT INTO CLIENTE VALUES(NULL, 'CARLOS AGUIAR', 'RUA AUGUSTO FILHO', 48);
INSERT INTO CLIENTE VALUES(NULL, 'JORGE GOMES', 'RUA ERNESTO TEIXEIRA', 12);
INSERT INTO CLIENTE VALUES(NULL, 'TIAGO SEGATO', 'RUA AUGUSTA', 9);
INSERT INTO CLIENTE VALUES(NULL, 'CAIO PROFESSOR', 'RUA DAMACENO FILHO', 3);
INSERT INTO CLIENTE VALUES(NULL, 'JALINE PROFESSORA', 'RUA LOPES LOBO', 45);

--- RESULTADO DA QUERY 
mysql> SELECT * FROM CLIENTE;
+-----------+-------------------+----------------------+--------+
| IDCLIENTE | NOME              | RUA                  | NUMERO |
+-----------+-------------------+----------------------+--------+
|         1 | CARLOS AGUIAR     | RUA AUGUSTO FILHO    |     48 |
|         2 | JORGE GOMES       | RUA ERNESTO TEIXEIRA |     12 |
|         3 | TIAGO SEGATO      | RUA AUGUSTA          |      9 |
|         4 | CAIO PROFESSOR    | RUA DAMACENO FILHO   |      3 |
|         5 | JALINE PROFESSORA | RUA LOPES LOBO       |     45 |
+-----------+-------------------+----------------------+--------+
5 rows in set (0.01 sec)


--INSERINDO DADOS NA TABELA PEDIDO
-- TIAGO COMPROU UM ARDUINO
INSERT INTO PEDIDO VALUES(NULL, 'ARDUINO', NOW(), 3);
INSERT INTO PEDIDO VALUES(NULL, 'PLACA MÃE', NOW(), 4);
INSERT INTO PEDIDO VALUES(NULL, 'PROCESSADOR', NOW(), 5);
INSERT INTO PEDIDO VALUES(NULL, 'MEMÓRIA DDR4', NOW(), 2);
INSERT INTO PEDIDO VALUES(NULL, 'PLACA DE VIDEO', NOW(), 1);


SELECT * FROM PEDIDO;

mysql> SELECT * FROM PEDIDO;
+----------+----------------+------------+------------+
| IDPEDIDO | DESCRICAO      | DATAPEDIDO | ID_CLIENTE |
+----------+----------------+------------+------------+
|        1 | ARDUINO        | 2019-10-03 |          3 |
|        2 | ARDUINO        | 2019-10-03 |          3 |
|        3 | PLACA MÃE      | 2019-10-03 |          4 |
|        4 | PROCESSADOR    | 2019-10-03 |          5 |
|        5 | MEMÓRIA DDR4   | 2019-10-03 |          2 |
|        6 | PLACA DE VIDEO | 2019-10-03 |          1 |
+----------+----------------+------------+------------+
6 rows in set (0.00 sec)


--- INSERINDO PRODUTO

INSERT INTO PRODUTO VALUES (NULL,'ARDUINO', 300.99);
INSERT INTO PRODUTO VALUES (NULL,'PLACA MÃE', 450.99);
INSERT INTO PRODUTO VALUES (NULL,'PROCESSADOR4', 700.99);
INSERT INTO PRODUTO VALUES (NULL,'MEMÓRIA DDR4', 150.99);
INSERT INTO PRODUTO VALUES (NULL,'PLACA DE VÍDEO', 1700.99);

SELECT * FROM PRODUTO;

mysql> SELECT * FROM PRODUTO;
+-----------+----------------+---------+
| IDPRODUTO | DESCRICAO      | PRECO   |
+-----------+----------------+---------+
|         1 | PLACA DE VÍDEO | 1700.99 |
|         2 | PLACA MÃE      |  450.99 |
|         3 | PROCESSADOR4   |  700.99 |
|         4 | MEMÓRIA DDR4   |  150.99 |
|         5 | PLACA DE VÍDEO | 1700.99 |
+-----------+----------------+---------+
5 rows in set (0.00 sec)


--INSERINDO DADOS NA TABELA ITEMPEDIDO
INSERT INTO ITEMPEDIDO VALUES(NULL,8 ,700.99, 3);
INSERT INTO ITEMPEDIDO VALUES(NULL,5 ,1700.99, 1);
INSERT INTO ITEMPEDIDO VALUES(NULL,2 ,450.99, 2);
INSERT INTO ITEMPEDIDO VALUES(NULL,1 ,200.99, 5);
INSERT INTO ITEMPEDIDO VALUES(NULL,4 ,700.99, 4);

SELECT * FROM ITEMPEDIDO;

mysql> SELECT * FROM ITEMPEDIDO;
+--------+------------+---------+------------+
| IDITEM | QUANTIDADE | VALOR   | ID_PRODUTO |
+--------+------------+---------+------------+
|      1 |          8 |  700.99 |          3 |
|      2 |          5 | 1700.99 |          1 |
|      3 |          2 |  450.99 |          2 |
|      4 |          1 |  200.99 |          5 |
|      5 |          4 |  700.99 |          4 |
+--------+------------+---------+------------+
5 rows in set (0.00 sec)